### ISSUE TITLE
Update flag cuts in lightcurve.py

### ISSUE THREAD

**Issue by MatSmithAstro** [MickaelRigault/ztfidr#1]
Hi Mickael, 

The definition to select good light-curve points in lightcurve.py (line 126) needs updating to match the new flag definition. 

```
 def get_lcdata(self, zp=None, in_mjdrange=None,
                       min_detection=None,
                       filters=None,
                       flagout=[1,2,4,8,256]):
```

should be `flagout=[1,2,4,8,16]`

This affects objects such as ZTF18acbvgqw, where all of the r-band data is no longer considered valid in the fitting.

Waves,

Mat

**Comment by MickaelRigault** [comment]
Done version 0.7.16
